### ISSUE TITLE
Restructure the project

### ISSUE THREAD

**Issue by lodo1995** [lodo1995/experimental.xml#1]
- Setup with DUB;
- Rename `experimental.xml` to `std.experimental.xml`;
- Add Makefile;

**Comment by burner** [comment]
what should the makefile do?

**Comment by lodo1995** [comment]
@burner Mainly compilation and execution of the test driver (which will be created as per issue #2 ). Maybe also as a wrapper for dub.

**Comment by burner** [comment]
sounds like a plan
