### ISSUE TITLE
[feature] XPATH support

### ISSUE THREAD

**Issue by wilzbach** [lodo1995/experimental.xml#11]
Just a question whether [XPath](https://en.wikipedia.org/wiki/XPath) will be part of the project?
It would help a lot to scrape HTML documents.

In Python is pretty easy with lxml:

http://docs.python-guide.org/en/latest/scenarios/scrape/
http://lxml.de/

**Comment by lodo1995** [comment]
It is not on the main todo list, but I find it really useful too.
When and if the main goals will be reached I will focus on extending the library, starting from either XPath or XSD.

Whether or not these extensions will be part of Phobos is another issue: the core library by itself will end up being pretty big, and I don't know if everybody is fine with such a big piece of code.

**Comment by wilzbach** [comment]
This issue was moved to dlang-community/experimental.xml#2
