### ISSUE TITLE
Controlling input duplication

### ISSUE THREAD

**Issue by lodo1995** [lodo1995/experimental.xml#13]
As it currently is, the slices returned by the various APIs refer to the same (possibly big) array passed as input to the `SliceLexer`. Given that most of the content of that array is not important for the application, it may be useful to have the possibility of duplicating the needed data, so that the original array can be deallocated at the end of the parsing.

Given the amount of duplicated names (tag names, attributes, ...) a string interning option may be worth having.

**Comment by lodo1995** [comment]
Commits adc40ca592273fd08d6f898091ae9ef77ca4eba2 and b5c4afc78b6fa6090f841cd6c209a293020ac5dd added options to decouple the output slices from the input at `Parser` or `XMLCursor` level. String interning, on the other side, is only useful in `XMLCursor`, and thus not available in `Parser`.

**Comment by burner** [comment]
nice, looks like stuff is taking shape.
