### ISSUE TITLE
Non-copyable ranges

### ISSUE THREAD

**Issue by lodo1995** [lodo1995/experimental.xml#17]
Commit 8dc3c0bdb570728841d15a89a72b72d025dc058d did break every testing (except unittests, which is why I didn't notice).

This is because that commit hid some postblit ctors. The change was motivated by the fact that you never want to implicitly copy the lexers/parsers/cursors. If you want to copy them, you have to explicitly use `save()`.

The problem is that `foreach` does an implicit copy of its input.

I guess that the only solution is to revert the changes to the ctors.

**Comment by burner** [comment]
I agree, revert it.

Additionally, I would make sure that all tests are always run. You don't have run the complete benchmark with all tries and stuff. Only run the benchmark code once, so you can see that it compiles and does not explode in your face.
