### ISSUE TITLE
Design by Introspection

### ISSUE THREAD

**Issue by burner** [lodo1995/experimental.xml#18]
https://github.com/lodo1995/experimental.xml/blob/master/source/std/experimental/xml/sax.d#L54

here you checking if something passed in has a specific method. What you invented is basically Design by Introspection. Andrei invented something similar, the only difference is that he uses hasMember. Maybe have a look at his DConf 2014 Talk. I bet this will come up in the review for the phobos inclusion ;-)

**Comment by lodo1995** [comment]
Found at DConf 2015. `hasMember` is more readable, but does not check for correctness of parameters.
Thus, the SAX parser would raise an error if the handler defines the method with a different signature which may be a good thing (prevents silent bugs). Currently, if the signature does not match, the handler method is silently ignored.

**Comment by burner** [comment]
fair enough
