### ISSUE TITLE
Restructure testing

### ISSUE THREAD

**Issue by lodo1995** [lodo1995/experimental.xml#2]
- Move the current testing code from unittests to a separate testing module
- Include the W3C XML Test Suite from https://www.w3.org/XML/Test/
- Include BOM handling, so that the Test Suite can be used

**Comment by lodo1995** [comment]
To be used completely, the XML Test Suite requires the ability to parse DTDs and external entities, so for now only part of it will be used in testing (even if I will copy all of it in the project).
For this reason, DTD parsing and entity substitution (at least for internal entities) gains a higher priority than before.

**Comment by burner** [comment]
for parsing that is true, but for lexing aka split the string into xml nodes all files should work. most likely

**Comment by lodo1995** [comment]
Closing; now the structure for testing is set up.
