### ISSUE TITLE
Appender enlarge

### ISSUE THREAD

**Issue by burner** [lodo1995/experimental.xml#20]
``` D
private void enlarge(size_t sz) {
    allocator.expandArray(arr, sz);
}
```

https://dlang.org/phobos/std_experimental_allocator.html#.expandArray

expandArray does what you implemented in enlarge. Maybe even remove enlarge all together.

**Comment by lodo1995** [comment]
You're right. I don't know why I didn't use it in the first place. I'll fix it.
The method will remain, as it also contains the logic to decide the expansion factor.

**Comment by burner** [comment]
No problem, sometimes you/me/everybody just misses stuff.

**Comment by burner** [comment]
+1
