### ISSUE TITLE
Investigate ICE when changing function protection

### ISSUE THREAD

**Issue by lodo1995** [lodo1995/experimental.xml#27]
Changing `std.experimental.xml.faststrings.fastEqual` from no protection specifier (defaults to `public`) to `package` or `package(std)` triggers an ICE (the compiler segfaults). This change should be allowed, as `fastEqual` is really meant for internal usage.
Trying to change the protection to `private` (wrong, as it is needed in other modules) correctly triggers a series of deprecations and compilation errors.

**Comment by wilzbach** [comment]
As Walter likes to say "It's not a bug, if it's not on Bugzilla" ;-)

**Comment by lodo1995** [comment]
@wilzbach I know. I didn't have time to create a reduced test case. When I'll have it, I'll submit a bug report.

**Comment by lodo1995** [comment]
Confirmed as DMD bug. Reported with reduced test case as issue 16348.

**Comment by Hackerpilot** [comment]
A link for lazy people: https://issues.dlang.org/show_bug.cgi?id=16348
