### ISSUE TITLE
Using assert to indicate error

### ISSUE THREAD

**Issue by NVolcz** [lodo1995/experimental.xml#30]
When parsing a broken XML document the following assertion failure is generated. Since assertion failure is non-recoverable an exception seems like better for the default.
´´´
core.exception.AssertError@../../../../.dub/packages/std-experimental-xml-master/std-experimental-xml/source/std/experimental/xml/cursor.d(500): Assertion failure
´´´

**Comment by lodo1995** [comment]
The error handler defaults to `assert(0)`, but is configurable. You can find an example in the [documentation](https://lodo1995.github.io/experimental.xml/std/experimental/xml.html) (look at the third example).

Just use `myParser.cursor(myErrorHandler)` to have a cursor that does whatever you want in case of error.

**Comment by NVolcz** [comment]
I meant that asserts are not supposed to signal errors on user input

**Comment by lodo1995** [comment]
Sorry. I may have misunderstood your point. The reason I decided to use `assert`s as the default callback is that they indicate code that should never be reached. This is the case, as if you didn't put an handler it means you are expecting your input to always be correct (it may not come from the user, but from an application which you trust).
If you know your input cannot be trusted, and want your application to be fault-tolerant, you should definitely put your own handler there.
But this is just my point of view, I may be wrong on what's better as a default. So I'll probably bring this to the attention of the reviewers, so I can have their feedback on this.
Thank you very much for giving your opinion.
