### ISSUE TITLE
Infinity loop

### ISSUE THREAD

**Issue by anton-dutov** [lodo1995/experimental.xml#35]
Some times, got infinity loop

    import std.stdio;
    import std.experimental.xml;

    void main()
    {
        auto content = import("1.xml");
        auto domBuilder = chooseParser!content.cursor.domBuilder;

        domBuilder.setSource(content);
        domBuilder.buildRecursive;

        auto dom = domBuilder.getDocument;
        auto lst = dom.getElementsByTagName("eb:MessageHeader");

        writeln(lst.length);
    }

**Comment by lodo1995** [comment]
I guess it's inside `getElementsByTagName`. Does it fail consistently when fed the same file? If the input file that causes the issues is small, could you upload it?

**Comment by anton-dutov** [comment]
Complex example from https://developer.sabre.com, stuck every time
`DMD64 D Compiler v2.071.2`
`dependency "std-experimental-xml" version="~>0.1.2"`

[1.xml.zip](https://github.com/lodo1995/experimental.xml/files/563390/1.xml.zip)

**Comment by jmdavis** [comment]
Oh. I just ran into this issue. Thanks for fixing it. :)

It would be nice if we could get another tagged release one of these days soon though, since dub now seems allergic to using `~master` and complains when you do.
