### ISSUE TITLE
Example isn't compiles

### ISSUE THREAD

**Issue by denizzzka** [lodo1995/experimental.xml#38]
First example from https://lodo1995.github.io/experimental.xml/std/experimental/xml.html returns
```
source/map.d(25,13): Error: no property 'lexer' for type 'string'
```

**Comment by WebFreak001** [comment]
bump - maybe release a new version?

**Comment by WebFreak001** [comment]
Well you could try out the example on the latest release: https://github.com/lodo1995/experimental.xml/blob/255caeaf4231fb66f4c81d23cd37814670ac2306/source/std/experimental/xml/package.d#L35

**Comment by wilzbach** [comment]
This issue was moved to dlang-community/experimental.xml#14

**Comment by denizzzka** [comment]
So, I should close this ticket.

**Comment by wilzbach** [comment]
Yes, I don't have any permissions here :/
