### ISSUE TITLE
BlockStatements and Empty lines

### ISSUE THREAD

**Issue by burner** [lodo1995/experimental.xml#8]
here I would at least suggest adding an additional empty line between the else statement and the next if.
Better would be if you only use { } for everything like if, while ...

sounds nitpicky but the quoted line is just hard to read and hard to change. Just let your editor create the curlies and be done with that.

https://github.com/lodo1995/experimental.xml/blob/master/source/std/experimental/xml/lexers.d#L81

**Comment by lodo1995** [comment]
Reminiscences of some time ago, when I used to put lots of effort into writing as few lines as possible.
I'll try to avoid this style.

Thank you for pointing it out.
